"""update users table

Revision ID: ace228b850af
Revises: c9b7f5b70acd
Create Date: 2023-03-08 12:41:22.304797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace228b850af'
down_revision = 'c9b7f5b70acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=32), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
