"""add userpass column

Revision ID: c9b7f5b70acd
Revises: 3b0023293746
Create Date: 2023-01-22 15:01:12.939769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b7f5b70acd'
down_revision = '3b0023293746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=32), nullable=False))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
